name: Update Mesh Inventory

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours (customize as needed)

jobs:
  update-mesh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests pyyaml

      - name: Run update_mesh_inventory.py
        env:
          TAILSCALE_API_KEY: ${{ secrets.TAILSCALE_API_KEY }}
          TAILSCALE_TAILNET: yourtailnet.tailscale.net  # CHANGE THIS!
        run: |
          python scripts/update_mesh_inventory.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/mesh-inventory-auto.md docs/mesh-inventory-auto.yaml
          git commit -m "Automated: Update mesh inventory" || echo "No changes to commit"
          git push